model:
  save: False
  load: False
  save_dir: "models/test"
  source_dir: "models/test"
  num_weather_params: 0
  epochs: 20
  batch_size: 16
  val_frac: 0.2
  test_frac: 0.1
  patience_val: 10
  optimizer: "Adam"
  dropout: 0.1
  plsr_components: 4
  layers:
    - width: 33
    - width: 64
      activation: "elu"
    - width: 32
      activation: "elu"
    - width: 16
      activation: "elu"
    - width: 8
      activation: "elu"
data:
  path: "C:\\Users\\emilm\\Documents\\NTNU\\4.klasse\\EIT\\data\\test_data.csv"
  last_year_key: "elg sett sum sette elg pr dag"
  this_year_key: "elg sett sum sette elg pr dag neste aar"
  weather_keys: []
  extra_data_keys: ["other_1", "other_2"]
