model:
  num_weather_params: 4
  epochs: 100
  batch_size: 32
  val_frac: 0.2
  test_frac: 0.1
  patience_val: 10
  optimizer: "Adam"
  dropout: 0.1
  layers:
    - width: 32
      activation: "relu"
    - width: 16
      activation: "relu"
data:
  path: "data/data.csv"
  last_year_key: "last_year"
  this_year_key: "this_year"
  weather_keys: ["w0", "w1", "w2", "w3"]
  extra_data_keys: ["other_1", "other_2"]
